name: cs229_project
channels:
  - defaults
#conda install -c anaconda py-xgboost
dependencies:
  - matplotlib=2.2.2
  - numpy=1.15.0
  - pip=10.0.1
  - python=3.6.6
  - scipy
  - pandas
  - py-xgboost
  - lightgbm
  - scikit-learn=0.19
  - nomkl